import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                fetch: 'readonly',
                AbortSignal: 'readonly',
                AbortController: 'readonly',
                setTimeout: 'readonly',
                clearInterval: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                console: 'readonly',
                process: 'readonly',
                global: 'readonly',
                Buffer: 'readonly',
                Image: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                HTMLElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLSpanElement: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLImageElement: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                setInterval: 'readonly',
                location: 'readonly',
            },
        },
        rules: {
            semi: ['error', 'always'],
            quotes: ['error', 'single', { avoidEscape: true }],
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
            eqeqeq: ['error', 'always'],
            'no-var': 'error',
            'prefer-const': 'error',
            'no-empty': 'warn',
            'no-useless-escape': 'off',
            indent: 'off',
            'comma-dangle': 'off',
            curly: 'off',
            'space-before-function-paren': 'off',
            'object-curly-spacing': 'off',
            'array-bracket-spacing': 'off',
            'eol-last': 'off',
            'no-dupe-keys': 'off',
        },
    },
    {
        ignores: ['node_modules/', 'known_faces/', 'uploads/', 'coverage/'],
    },
];
